// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ6DBwDy8ukkFPYODCAdqb9WOyBxlO5qk',
    appId: '1:698033405153:web:3b2cf5039bbbd937db4ba0',
    messagingSenderId: '698033405153',
    projectId: 'aab-e-hayat-69705',
    authDomain: 'aab-e-hayat-69705.firebaseapp.com',
    storageBucket: 'aab-e-hayat-69705.firebasestorage.app',
    measurementId: 'G-5BJSE436E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCT8gKXPDANcNkpJz3YsRndpWi6E1XowE',
    appId: '1:698033405153:android:55402402b6edba0ddb4ba0',
    messagingSenderId: '698033405153',
    projectId: 'aab-e-hayat-69705',
    storageBucket: 'aab-e-hayat-69705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY6marntDNzSUL34puEOKp-2ui7t6wOYs',
    appId: '1:698033405153:ios:0f6e2a7aa931aa61db4ba0',
    messagingSenderId: '698033405153',
    projectId: 'aab-e-hayat-69705',
    storageBucket: 'aab-e-hayat-69705.firebasestorage.app',
    iosBundleId: 'com.example.aabehayatVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY6marntDNzSUL34puEOKp-2ui7t6wOYs',
    appId: '1:698033405153:ios:0f6e2a7aa931aa61db4ba0',
    messagingSenderId: '698033405153',
    projectId: 'aab-e-hayat-69705',
    storageBucket: 'aab-e-hayat-69705.firebasestorage.app',
    iosBundleId: 'com.example.aabehayatVendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ6DBwDy8ukkFPYODCAdqb9WOyBxlO5qk',
    appId: '1:698033405153:web:204a83f13a79520ddb4ba0',
    messagingSenderId: '698033405153',
    projectId: 'aab-e-hayat-69705',
    authDomain: 'aab-e-hayat-69705.firebaseapp.com',
    storageBucket: 'aab-e-hayat-69705.firebasestorage.app',
    measurementId: 'G-C6Y66NHRSK',
  );
}
